2025-05-19 09:47:29,511 - INFO - Epoch 1/10 | Teacher Forcing Ratio: 0
Training:   0%|[32m                                                                                                                                     [0m| 0/346 [00:00<?, ?batch/s][0m
Traceback (most recent call last):
  File "/home/jay/miniconda3/envs/Sequence/lib/python3.10/site-packages/graphviz/backend/execute.py", line 78, in run_check
    proc = subprocess.run(cmd, **kwargs)
  File "/home/jay/miniconda3/envs/Sequence/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/jay/miniconda3/envs/Sequence/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/jay/miniconda3/envs/Sequence/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('dot')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jay/da6401_assignment3/train.py", line 148, in <module>
    main()
  File "/home/jay/da6401_assignment3/train.py", line 133, in main
    train_loss, train_accuracy = train_one_epoch(model, train_loader, optimizer, criterion, CLIP, tf_ratio)
  File "/home/jay/da6401_assignment3/train.py", line 36, in train_one_epoch
    make_dot(output, params=dict(model.named_parameters())).render("model_architecture", format="png")
  File "/home/jay/miniconda3/envs/Sequence/lib/python3.10/site-packages/graphviz/_tools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "/home/jay/miniconda3/envs/Sequence/lib/python3.10/site-packages/graphviz/rendering.py", line 122, in render
    rendered = self._render(*args, **kwargs)
  File "/home/jay/miniconda3/envs/Sequence/lib/python3.10/site-packages/graphviz/_tools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "/home/jay/miniconda3/envs/Sequence/lib/python3.10/site-packages/graphviz/backend/rendering.py", line 326, in render
    execute.run_check(cmd,
  File "/home/jay/miniconda3/envs/Sequence/lib/python3.10/site-packages/graphviz/backend/execute.py", line 81, in run_check
    raise ExecutableNotFound(cmd) from e
graphviz.backend.execute.ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH
